config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users

  get 'settings_profile' => 'settings#profile'
  post 'settings_profile' => 'settings#set_change_profile'
  get 'register' => 'sessions#signup'
  post 'register' => 'sessions#register'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'admin/index'
  get 'home/index'
  get 'pages/index'
  get 'pages/new'
  get 'pages/setting'
  get 'pages/index'
  get 'pages/new'
  get '/auth/:provider/callback', to: 'sessions#auth'
  get 'disconnect/:provider' => 'settings#disconnect', as: :disconnect
  delete 'logout' => 'sessions#destroy'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.to_s.downcase }
  mount_uploader :picture, PictureUploader
  validates(:name, presence: true, length: {maximum: 255})
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true)
  validates :password, presence: true, length: {minimum: 6}, confirmation: true, allow_nil: true
  validate :picture_size
  has_secure_password

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :is_admin?
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  before_action :require_login, only: [:index, :edit, :update]

  private

  def require_login
    if !logged_in?
      redirect_to login_url
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def is_admin?
    if logged_in? && current_user.admin.nil?
      redirect_to root_path
    end
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def new
  end

  def setting
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user.admin? ? admin_index_path : root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'sessions/new'
    end
  end

  def auth
    begin
      @user = from_omniauth(request.env['omniauth.auth'])
      if (session[:user_id].nil?)
        session[:user_id] = @user.id
      end
      flash[:success] = "Connect #{request.env['omniauth.auth'].provider.capitalize} Successfully."
    rescue
      flash.now[:warning] = 'There was an error while trying to authenticate you...'
    end

    redirect_to root_path
  end

  def signup
    @user = User.new
  end

  def register
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'User was successfully created.'
      redirect_to register_path
    else
      render 'signup'
    end
  end

  def auth_failure
    redirect_to root_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      @current_user = nil
    end
    redirect_to login_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def profile
    @user = current_user
    @user_face = user_has_social('facebook')
    @user_twitter = user_has_social('twitter')
    @user_google = user_has_social('google')
    @user_instagram = user_has_social('instagram')
  end

  def set_change_profile
    @user = current_user

    if @user.update_attributes(user_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to settings_profile_path
    else
      render 'settings/profile'
    end
  end

  def disconnect
    begin
      @user = dis_connect(current_user.id, params[:provider])
      flash[:success] = "Disconnect #{params[:provider].capitalize} Successfully."
    rescue
      flash.now[:warning] = "There was an error while trying to disconnect #{params[:provider].capitalize} ..."
    end

    redirect_to settings_profile_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'User was successfully created.'
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        if user_params[:picture]
          @user.update(:picture => user_params[:picture], :image_url => nil)
        end

        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'User was successfully destroyed.'
    redirect_to admin_index_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  def from_omniauth(auth_hash)
    user = User.find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.name = auth_hash['info']['name']
    user.image_url = auth_hash['info']['image']
    user.is_connect = true
    user.user_id = user.nil? ? nil : user.id
    user.save(:validate => false)
    user
  end

  def dis_connect(user_id, provider)
    user = User.find_by(user_id: user_id, provider: provider)
    user.is_connect = false
    user.save(:validate => false)
    user
  end

  private

  def get_social_location_for(provider, location_hash)
    case provider
      when 'linkedin'
        location_hash['name']
      else
        location_hash
    end
  end

  def get_social_url_for(provider, urls_hash)
    case provider
      when 'linkedin'
        urls_hash['public_profile']
      else
        urls_hash[provider.capitalize]
    end
  end

  def user_has_social(provider)
    user = User.find_by(user_id: current_user.id, provider: provider)

    if user.nil?
      user_social = User.find_by(id: current_user.id, provider: provider)
    else
      user_social = nil
    end

    user_social
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% provide(:title, "Listing Users") %>

<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <span class="glyphicon glyphicon-eye-open"></span>
          <%= link_to 'Show', user %>
        </td>
        <td>
          <span class="glyphicon glyphicon-edit"></span>
          <%= link_to 'Edit', edit_user_path(user) %>
        </td>
        <% if current_user.admin? && !current_user?(user) %>
            <td>
              <span class="glyphicon glyphicon-remove"></span>
              <%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %>
            </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-plus-sign'), new_user_path, :class => "btn btn-primary" %>

app/views/home/index.html.erb
<% provide(:title, "Home Page") %>

<h1>Home#index</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Test App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li class="avatar">
              <% if current_user.picture? %>
                  <%= image_tag current_user.picture.url, alt: current_user.name %>
              <% elsif current_user.image_url  %>
                  <%= image_tag current_user.image_url, alt: current_user.name %>
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", settings_profile_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Register", register_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/pages/index.html.erb
<% provide(:title, "Home page") %>
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<% provide(:title, "Home page") %>
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/setting.html.erb
<h1>Pages#setting</h1>
<p>Find me in app/views/pages/setting.html.erb</p>

app/views/settings/_profile_form.html.erb
<div class="setting-profile">
  <div class="col-md-10">
    <%= form_for(@user, url: settings_profile_path, html: {method: 'post'}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password %><br>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <div class="picture">
          <%= f.label 'Avatar' %><br>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
        </div>

        <div class="setting-social-connect">
          <label>Social Networks</label>

          <div class="connection">
            <div class="field">
              <% if @user_face && @user_face.is_connect? %>
                  <p class="label">Facebook connected</p>
                  <%= link_to 'Disconnect', disconnect_path(:provider => 'facebook'), :class => "thick badge-add-fb-timeline switch_on" %>
              <% else %>
                  <p class="label">Facebook not connected</p>
                  <%= link_to 'Connect Now', '/auth/facebook', :class => "btn badge-add-fb-timeline switch_of" %>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>

          <div class="connection">
            <div class="field">
              <% if @user_twitter && @user_twitter.is_connect? %>
                  <p class="label">Twitter connected</p>
                  <%= link_to 'Disconnect', disconnect_path(:provider => 'twitter'), :class => "thick badge-add-fb-timeline switch_on" %>
              <% else %>
                  <p class="label">Twitter not connected</p>
                  <%= link_to 'Connect Now', '/auth/twitter', :class => "btn badge-add-fb-timeline switch_of" %>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>

          <div class="connection">
            <div class="field">
              <% if @user_google && @user_google.is_connect? %>
                  <p class="label">Google+ connected</p>
                  <%= link_to 'Disconnect', disconnect_path(:provider => 'google'), :class => "thick badge-add-fb-timeline switch_on" %>
              <% else %>
                  <p class="label">Google+ not connected</p>
                  <%= link_to 'Connect Now', '/auth/google', :class => "btn badge-add-fb-timeline switch_of" %>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>

          <div class="connection">
            <div class="field">
              <% if @user_instagram && @user_instagram.is_connect? %>
                  <p class="label">Instagram connected</p>
                  <%= link_to 'Disconnect', disconnect_path(:provider => 'instagram'), :class => "thick badge-add-fb-timeline switch_on" %>
              <% else %>
                  <p class="label">Instagram not connected</p>
                  <%= link_to 'Connect Now', '/auth/instagram', :class => "btn badge-add-fb-timeline switch_of" %>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>

        <div class="actions col-md-4 row">
          <%= f.submit "Save Changes", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

app/views/settings/profile.html.erb
<h1>Setting Profile</h1>

<% provide(:title, 'Setting - Account') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'profile_form' %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if  object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, html: {multipart: true}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password %><br>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <div class="picture">
          <%= f.label 'Avatar' %><br>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit "Update", class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $('#user_picture').bind('change', function () {
        var size_in_megabytes = this.files[0].size / 1024 / 1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/users/edit.html.erb
<% provide(:title, "Update Profile") %>

<h1>Update Profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<% provide(:title, "New User") %>

<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>